name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - legacy
      - main

jobs:
  development:
    name: Development Stage
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Deploy to development environment
        run: |
          # Add your deployment script here
          echo "Deployment to development environment"

  testing:
    name: Testing Stage
    if: github.ref == 'refs/heads/legacy'
    runs-on: ubuntu-latest

    needs: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run integration tests
        run: npm run test:integration

      - name: Deploy to testing environment
        run: |
          # Add your deployment script here
          echo "Deployment to testing environment"

  production:
    name: Production Stage
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    needs: testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Deploy to production environment
        run: |
          # Add your deployment script here
          echo "Deployment to production environment"
