name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - legacy
      - main

jobs:
  development:
    name: Development Stage
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: npm install

      # - name: Run unit tests
      #   run: npm test

      - name: Build application
        run: npm run build

      - name: Push to Legacy Branch
        run: |
          git checkout legacy
          git merge dev --no-edit
          git push origin legacy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to development environment
        run: |
          # Add your deployment script here
          echo "Deployment to development environment"
          # git push origin dev:legacy # Push changes from dev to legacy branch
  
  testing:
    name: Testing Stage
    # if: github.ref == 'refs/heads/legacy'
    runs-on: ubuntu-latest

    needs: development

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: npm install

      # - name: Run integration tests
      #   run: npm run test:integration

      - name: Deploy to testing environment
        run: |
          # Add your deployment script here
          echo "Deployment to testing environment"

  production:
    name: Production Stage
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    needs: testing

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: npm install

      - name: Deploy to production environment
        run: |
          # Add your deployment script here
          echo "Deployment to production environment"
